#include QMK_KEYBOARD_H

// mod taps
#define MA LCTL_T(KC_A)
#define MS LALT_T(KC_S)
#define MD LGUI_T(KC_D)
#define MF LSFT_T(KC_F)
#define MJ RSFT_T(KC_J)
#define MK RGUI_T(KC_K)
#define ML LALT_T(KC_L)
#define MSCLN RCTL_T(KC_SCLN)

// space layer 1
#define SPC_L1 LT(1, KC_SPC)

// osm
// #define OSM_ALT OSM(MOD_LALT)
// #define OSM_GUI OSM(MOD_LGUI)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
 [0] = LAYOUT_ortho_5x15(
	KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_F10,  KC_F11,  KC_F12,  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    CG_TOGG,
	KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_F7,   KC_F8,   KC_F9,   KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_EQL,
	KC_LSFT, MA,      MS,      MD,      MF,      KC_G,    KC_F4,   KC_F5,   KC_F6,   KC_H,    MJ,      MK,      ML,      MSCLN,   KC_QUOT,
	KC_LCTL, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_F1,   KC_F2,   KC_F3,   KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_MINS,
	KC_LCTL, KC_NO,   KC_NO,   KC_ESC,  KC_ESC,  SPC_L1,  KC_LBRC, KC_BSLS, KC_RBRC, KC_ENT,  KC_BSPC, KC_DEL,  KC_NO,   KC_NO,   KC_NO
 ),
 [1] = LAYOUT_ortho_5x15(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_BOOT
 ),
};


